### ISSUE TITLE
🐛 Bug Report: @appwrite.io/fonts is private or missing

### ISSUE THREAD

**Issue by omar2205** [appwrite/pink#53]
### 👟 Reproduction steps

```
@appwrite.io/fonts is not in the npm registry, or you have no permission to fetch it.
```

### 👍 Expected behavior

N/A

### 👎 Actual Behavior

N/A

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by ArmanNik** [comment]
Hi @omar2205 thank you for bringing this up :) 

`@appwrite.io/fonts` is just a bundle of Google fonts that gets created to avoid importing all the fonts in every sub-repo. That's why the package is not published on npm :+1: 

We separated the fonts from Pink Design so users could use their own. 
If you wish to have the same fonts as Pink Design, at the moment, we're using `inter`, `poppins`, and `source-code-pro` 
from Google Fonts :blush:

**Comment by ArmanNik** [comment]
@omar2205 That's interesting :thinking:  

Where did you call `npm install` from? It should run without problems in the main repo, but if you run in from the kitchen sink folder, it makes sense why you got that error, considering the fonts are created on build :+1:

**Comment by omar2205** [comment]
I guess I didn't do `npm i` in pink dir.
